@startuml
autonumber
actor "Timer" as TM

activate TM
activate ":System"
TM -> ":System" : Upon reaching the time limit, the automatic payment process starts, \nmaking the payment by bank transfer to the freelancer account,\nsending him an e-mail with a detailed invoice and saving the \norganization payment.
deactivate TM
@enduml
