@startuml
autonumber

participant "org:Organization" as OR
participant "trans:PaymentTransactionList" as TLIST
participant "m_ListPay:List<PaymentTransaction>" as LIST
participant "transaction:PaymentTransaction" as TRA
participant "freel:Freelancer" as FREEL
participant "free:Freelancer" as FREE


[o-> OR: calculateDeviationP(free, mean)
activate OR

OR -> OR : deviation = 0
OR -> OR : counter = 0
OR -> OR : trans = getPaymentTransactionList()
OR -> TLIST : m_ListPay = getPaymentTransactions()
activate TLIST
deactivate TLIST

loop [ For each Transaction ]

OR -> LIST : transaction = get(i)
activate  LIST
deactivate LIST

OR -> TRA : freel = getFreelancer()
activate  TRA
deactivate TRA

OR -> FREEL : idFreel = getId()
activate  FREEL
deactivate FREEL

OR -> FREE : idFree = getId()
activate  FREE
deactivate FREE

opt [ idFree.equals(idFreel) ]

OR -> TRA : value = getValue()
activate  TRA
deactivate TRA

OR -> OR : deviation = (value-mean)^2 + deviation
OR -> OR : counter++

end
end loop

OR -> OR : deviation = Math.sqrt(deviation / counter)


<-- OR : deviation
deactivate OR

@enduml
